services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=America/New_York
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
    restart: unless-stopped

  alert-api:
    build: ./alert-api
    container_name: alert-api
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=mysql
      - DB_USER=grafana
      - DB_PASSWORD=grafana
      - DB_NAME=grafana
      - TZ=America/New_York
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=grafana
      - TZ=America/New_York
    volumes:
      - mysql-storage:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-config:/etc/prometheus
    environment:
      - TZ=America/New_York
    ports:
      - 9090:9090

volumes:
      grafana-data: {}
      grafana-config: {}
      mysql-storage: {}
      prometheus-config: {}